package laundry;

import java.awt.Desktop;
import java.awt.GraphicsEnvironment;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author INDES
 */
public class home_admin extends javax.swing.JFrame {

    private static final DateTimeFormatter smpdtfmt = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    LocalDateTime tglsekarang = LocalDateTime.now();
    private final String ltanggal = smpdtfmt.format(tglsekarang);

    String pel;
    private int xx;
    private int xy;

    public home_admin(String parameter){
        initComponents();
        wel.setText(parameter);
        }
   
    public home_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tanggalnya = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        wel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        pelanggan = new javax.swing.JMenu();
        jenis_cucian = new javax.swing.JMenu();
        penerimaan = new javax.swing.JMenu();
        transaksi = new javax.swing.JMenu();
        laporan = new javax.swing.JMenu();
        tentang = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(321, 74));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(50, 81, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jl. Raya Sukowati No 20. Sragen. Jawa-Tengah");
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 800, 30));

        tanggalnya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggalnya.setForeground(new java.awt.Color(204, 0, 0));
        tanggalnya.setText("tgl");
        getContentPane().add(tanggalnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        wel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wel.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(wel)
                .addContainerGap(1216, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(wel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 10));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Laundry YUSNITA");
        jLabel2.setMaximumSize(new java.awt.Dimension(705, 94));
        jLabel2.setMinimumSize(new java.awt.Dimension(705, 94));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 90));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\INDES\\Documents\\New Folder\\Laundry-master\\src\\laundry\\Icon\\icon mesin cuci.jpeg")); // NOI18N
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 560));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setAlignmentY(0.5F);

        master.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        master.setForeground(new java.awt.Color(102, 0, 204));
        master.setText("Pengguna");
        master.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        master.setMaximumSize(new java.awt.Dimension(153, 32767));
        master.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                masterMenuSelected(evt);
            }
        });
        master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masterMousePressed(evt);
            }
        });
        jMenuBar1.add(master);

        pelanggan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        pelanggan.setForeground(new java.awt.Color(102, 0, 204));
        pelanggan.setText("Pelanggan");
        pelanggan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pelanggan.setMaximumSize(new java.awt.Dimension(153, 32767));
        pelanggan.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                pelangganMenuSelected(evt);
            }
        });
        pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pelangganMousePressed(evt);
            }
        });
        jMenuBar1.add(pelanggan);

        jenis_cucian.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        jenis_cucian.setForeground(new java.awt.Color(102, 0, 204));
        jenis_cucian.setText("Jenis Cucian");
        jenis_cucian.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jenis_cucian.setMaximumSize(new java.awt.Dimension(153, 32767));
        jenis_cucian.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jenis_cucianMenuSelected(evt);
            }
        });
        jenis_cucian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jenis_cucianMousePressed(evt);
            }
        });
        jMenuBar1.add(jenis_cucian);

        penerimaan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        penerimaan.setForeground(new java.awt.Color(102, 0, 204));
        penerimaan.setText("Order Masuk");
        penerimaan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        penerimaan.setMaximumSize(new java.awt.Dimension(165, 32767));
        penerimaan.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                penerimaanMenuSelected(evt);
            }
        });
        penerimaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                penerimaanMousePressed(evt);
            }
        });
        jMenuBar1.add(penerimaan);

        transaksi.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        transaksi.setForeground(new java.awt.Color(102, 0, 204));
        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transaksi.setMaximumSize(new java.awt.Dimension(153, 32767));
        transaksi.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                transaksiMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                transaksiMenuSelected(evt);
            }
        });
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transaksiMousePressed(evt);
            }
        });
        jMenuBar1.add(transaksi);

        laporan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        laporan.setForeground(new java.awt.Color(102, 0, 204));
        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        laporan.setMaximumSize(new java.awt.Dimension(153, 32767));
        laporan.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                laporanMenuSelected(evt);
            }
        });
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                laporanMousePressed(evt);
            }
        });
        jMenuBar1.add(laporan);

        tentang.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        tentang.setForeground(new java.awt.Color(102, 0, 204));
        tentang.setText("Tentang");
        tentang.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tentang.setMaximumSize(new java.awt.Dimension(153, 32767));
        tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tentangMousePressed(evt);
            }
        });
        jMenuBar1.add(tentang);

        exit.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        exit.setForeground(new java.awt.Color(102, 0, 204));
        exit.setText("Keluar");
        exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit.setMaximumSize(new java.awt.Dimension(153, 32767));
        exit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                exitMenuSelected(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_masterMenuSelected
        
    }//GEN-LAST:event_masterMenuSelected

    private void pelangganMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_pelangganMenuSelected
        
    }//GEN-LAST:event_pelangganMenuSelected

    private void jenis_cucianMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jenis_cucianMenuSelected
        
    }//GEN-LAST:event_jenis_cucianMenuSelected

    private void penerimaanMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_penerimaanMenuSelected
        
    }//GEN-LAST:event_penerimaanMenuSelected

    private void transaksiMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_transaksiMenuCanceled

    }//GEN-LAST:event_transaksiMenuCanceled

    private void transaksiMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_transaksiMenuSelected
        
    }//GEN-LAST:event_transaksiMenuSelected

    private void laporanMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_laporanMenuSelected
        
    }//GEN-LAST:event_laporanMenuSelected

    private void exitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_exitMenuSelected
        
    }//GEN-LAST:event_exitMenuSelected

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

    }//GEN-LAST:event_exitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tanggalnya.setText(ltanggal);
    }//GEN-LAST:event_formWindowOpened

    private void masterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterMousePressed
        this.setVisible(true);
        new pengguna().setVisible(true);
    }//GEN-LAST:event_masterMousePressed

    private void pelangganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelangganMousePressed
        this.setVisible(true);
        new pelanggan().setVisible(true);
    }//GEN-LAST:event_pelangganMousePressed

    private void jenis_cucianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jenis_cucianMousePressed
        this.setVisible(true);
        new jenis_cucian().setVisible(true);
    }//GEN-LAST:event_jenis_cucianMousePressed

    private void penerimaanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penerimaanMousePressed
        this.setVisible(true);
        new penerimaan().setVisible(true);
    }//GEN-LAST:event_penerimaanMousePressed

    private void transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMousePressed
        this.setVisible(true);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_transaksiMousePressed

    private void laporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMousePressed
        if(Desktop.isDesktopSupported()){
            try{
                Desktop.getDesktop().browse(new URL("http://localhost/Laundry/laporan.php").toURI());
            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_laporanMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Konfirmasi Keluar Aplikasi",
            "Yakin untuk keluar dari program",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMousePressed

    private void tentangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tentangMousePressed
        JOptionPane.showMessageDialog(this,
           "-TUGAS PEMROGRAMAN OPEN SOURCE\n",
                  "DESY YUSNITA",
                JOptionPane.YES_OPTION);
    }//GEN-LAST:event_tentangMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jenis_cucian;
    private javax.swing.JMenu laporan;
    public javax.swing.JMenu master;
    private javax.swing.JMenu pelanggan;
    private javax.swing.JMenu penerimaan;
    private javax.swing.JLabel tanggalnya;
    private javax.swing.JMenu tentang;
    private javax.swing.JMenu transaksi;
    public static javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
